### ISSUE TITLE
Out-of-date babbage.cs.qc.cuny.edu URLs in README.md

### ISSUE THREAD

**Issue by vinc17fr** [cvickery/IEEE-754#7]
The babbage.cs.qc.cuny.edu URLs in README.md no longer work.

I can see that the "IEEE-754 Analysis" page is available at https://ysangkok.github.io/IEEE-754/index.xhtml

**Comment by cvickery** [comment]
Thank you so much for pointing this out! I did an incomplete job of migrating the site to my personal website when I retired from Queens College and had to give up my .edu web server. I think I've got everything in order now, but do report any further issues that you see.

Chris Vickery
August 29, 2024

**Comment by vinc17fr** [comment]
Thanks. There are 2 issues with https://christophervickery.com/IEEE-754/FAQ/
- This web page is encoded as UTF-8, but this charset isn't announced anywhere (neither in the HTTP headers nor in the web page), so that Firefox assumes that it is windows-1252.
- The link https://christophervickery.com/IEEE-754.old/References.xhtml#tables from this page gives a 404 Not Found error.

**Comment by cvickery** [comment]
Thanks again for your reports!
I think I’ve cleaned up the charset and link issues but, if you don’t mind, I’ll wait to get verification from you (by reply to this email)  before closing the report on github.

Chris

On Aug 29, 2024, at 6:07 PM, Vincent Lefèvre ***@***.***> wrote:


* This email originates from a sender outside of CUNY. Verify the sender before replying or clicking on links and attachments. *


Thanks. There are 2 issues with https://christophervickery.com/IEEE-754/FAQ/

  *   This web page is encoded as UTF-8, but this charset isn't announced anywhere (neither in the HTTP headers nor in the web page), so that Firefox assumes that it is windows-1252.
  *   The link https://christophervickery.com/IEEE-754.old/References.xhtml#tables from this page gives a 404 Not Found error.

**Comment by vinc17fr** [comment]
The charset is fixed, but not the link on "is still there" for Kevin's charts. It is currently https://christophervickery.com/IEEE-754.old/References.xhtml#tables instead of https://christophervickery.com/IEEE-754/IEEE-754.old/References.xhtml#tables (the "IEEE-754" part is missing in the URL). Also, "chart" should be in plural.

**Comment by cvickery** [comment]
Well, I worked on it more, and it’s looking better to me now. I still see some 404’s, but those seem to be browser-cache issues.

I added links to Bartosz Ciechanowski’s IEEE-754 tutorial and visualization tool in the FAQ page<https://christophervickery.com/IEEE-754/faq.html>. If you haven’t seen them before, I think you’ll find them interesting.

Thanks again for your valuable feedback, and do let me know what else I’ve missed!

Chris Vickery

On Aug 30, 2024, at 2:41 AM, Vincent Lefèvre ***@***.***> wrote:


* This email originates from a sender outside of CUNY. Verify the sender before replying or clicking on links and attachments. *


The charset is fixed, but not the link on "is still there" for Kevin's charts. It is currently https://christophervickery.com/IEEE-754.old/References.xhtml#tables instead of https://christophervickery.com/IEEE-754/IEEE-754.old/References.xhtml#tables (the "IEEE-754" part is missing in the URL). Also, "chart" should be in plural.
